---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy1
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: mycnt
          image: shaikmustafa/paytm:movie
          ports:
            - containerPort: 80
